---
name: "Gradle build"
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "Gradle build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Generate random keys"
        shell: bash
        run: |
          rm -f -- './keystore.jks'
          keytool -genkey -keystore './keystore.jks' -keyalg 'RSA' -keysize '2048' -validity '7300' -alias 'random-temp-key' -dname 'C=US, O=ale5000-variable, OU=Android, CN=Android' -storepass 'temp-pass' -keypass 'temp-pass'
      - name: "Gradle build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "randomSign build"
